kind: Service
apiVersion: v1
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
      app: optisam-nifi
  metadata:
    name: svc-optisam-nifi
    labels:
      run: optisam-nifi
    annotations:
      description: The web server's http port.

# - kind: ImageStream
#   apiVersion: v1
#   metadata:
#     name: nifi
#     labels:
#       app: nifi
# - apiVersion: v1
#   kind: BuildConfig
#   metadata:
#     labels:
#       app: nifi
#     name: nifi
#   spec:
#     nodeSelector:
#     output:
#       to:
#         kind: ImageStreamTag
#         name: "nifi:latest"
#     postCommit: {}
#     resources: {}
#     runPolicy: Serial
#     source:
#       binary: {}
#       type: Binary
#     strategy:
#       dockerStrategy:
#         from:
#           kind: ImageStreamTag
#           name: ${NIFI_BASE_IMAGE}
#           namespace: ${IMAGE_STREAM_NAMESPACE}
##     triggers: {}
#######

parameters:
- name: CPU_REQUEST
  description: "Minimum amount of CPU that the container may consume. Unit (m) has to be included."
  value: "600m"
  required: true
- name: CPU_LIMIT
  description: "Maximum amount of CPU that the container may consume. Unit (m) has to be included."
  value: "1000m"
  required: true
- name: MEMORY_REQUEST
  description: "Minimum amount of memory that the container may consume. Unit (Mi, Gi) has to be included."
  value: "1600Mi"
  required: true
- name: MEMORY_LIMIT
  description: "Maximum amount of memory that the container may consume. Unit (Mi, Gi) has to be included."
  value: "2000Mi"
  required: true
- name: NIFI_JAVA_XMS
  description: "Startup heap to be requested by the JVM."
  value: "-Xms512m"
  required: true
- name: NIFI_JAVA_XMX
  description: "Maximum heap to be requested by the JVM."
  value: "-Xmx1024m"
- name: NIFI_JVM_HEAP_INIT
  description: "Minimum Heap Value"
  value: "512m"
  required: true
- name: NIFI_JVM_HEAP_MAX
  description: "Maximum Heap Value"
  value: "2048m"        
  required: true
- name: NIFI_TIMEZONE
  description: "Timezone to be used by the JVM."
  value: "-Duser.timezone=Europe/Berlin"
  required: true
- name: TAG
  description: Tag for Docker image
  value: "dev"
  required: true
- name: ENV
  description: Env for deployment
  value: "dev"
  required: true
- name: REPLICAS
  description: Pod replica count
  value: "1"
  required: true
- name: DOCKER_REGISTRY
  description: Artifactory URL to download images
  value: "dockerfactory-unstable-iva.si.francetelecom.fr"
  required: true  
