kind: Service
apiVersion: v1
spec:
  ports:
      name: web
      port: 8080
      targetPort: 8080
    selector:
      app: optisam-nifi
metadata:
  name: svc-optisam-nifi
  labels:
  	run: optisam-nifi
  annotations:
  	description: The web server's http port.
