apiVersion: apps/v1
kind: Deployment
metadata:
  name: optisam-nifi
spec:
  replicas: 1
  template:
    metadata:
          spec:
      containers:
      - name: gitea-container
        image: gitea/gitea:1.4
