kind: Service
apiVersion: v1
metadata:
name: svc-optisam-meta
annotations:
  description: Exposes and load balances the application pods
  labels:
        run: optisam-meta
spec:
    ports:
        - name: api
          port: 80
          targetPort: 8080
          protocol: TCP
      selector:
        app: optisam-meta
  
  parameters:
  - name: TAG
    description: Tag for Docker image
    value: "latest"
    required: true
  - name: ENV
    description: Env for deployment
    required: true
  - name: REPLICAS
    description: Pod replica count
    value: "1"
    required: true
  - name: DOCKER_REGISTRY
    description: Artifactory URL to download images
    value: "dockerfactory-unstable-iva.si.francetelecom.fr"
    required: true
